### ISSUE TITLE
ユーザー新規登録画面の表示でエラーが出ます

### ISSUE THREAD

**Issue by T-Yuto** [watcher041/flema75d#18]
form_forの誕生日部分でエラーが出ています。
enum実装時に影響で読み取りがずれていると考えてます。
ja.ymlファイルを
https://qiita.com/yoshinoritera55/items/49a442414dda26f1fd81
の記事を参考に編集していただければと思います。

**Comment by T-Yuto** [comment]
Qiita記事参考に仮のブランチで実装してみましたが、
ユーザーが登録されません。

**Comment by tak-shimizu10** [comment]
https://gyazo.com/c25a3770129479566b8c87f05b10da2f
ja.ymlを上記のように編集してます。
これでいけるでしょうか？
